#!/bin/bash

# Set paths
REFERENCE="/home/sydt/scratch/alignment/genome_index/GCF_049852395.1_HU_Pman_BW_mat_3.1_genomic.fna"
ORIGINAL_VCF="/home/sydt/scratch/mgpl_file/top_snps_selection/ind999/peromyscus_ind999_top5000_snps.vcf.gz"
BAM_DIR="/home/sydt/scratch/mgpl_file/add_known_genome/aligned"
OUTPUT_DIR="/home/sydt/scratch/mgpl_file/top_snps_selection/ind999"

cd $OUTPUT_DIR

# Step 1: Create a list of target SNP positions from original VCF
bcftools query -f '%CHROM\t%POS\n' $ORIGINAL_VCF > target_snps.txt

# Step 2: Process leucopus.bam
bcftools mpileup -f $REFERENCE \
    -T target_snps.txt \
    $BAM_DIR/leucopus.bam 2>/dev/null | \
    bcftools call -c -Oz -o leucopus_temp.vcf.gz

# Fix sample name
bcftools reheader -s <(echo "leucopus") leucopus_temp.vcf.gz -o leucopus.vcf.gz
tabix -f leucopus.vcf.gz

# Step 3: Process maniculatus.bam
bcftools mpileup -f $REFERENCE \
    -T target_snps.txt \
    $BAM_DIR/maniculatus.bam 2>/dev/null | \
    bcftools call -c -Oz -o maniculatus_temp.vcf.gz

# Fix sample name
bcftools reheader -s <(echo "maniculatus") maniculatus_temp.vcf.gz -o maniculatus.vcf.gz
tabix -f maniculatus.vcf.gz

# Step 4: Merge all three VCFs
bcftools merge $ORIGINAL_VCF leucopus.vcf.gz maniculatus.vcf.gz -Oz -o final_merged.vcf.gz
tabix -f final_merged.vcf.gz

# Step 5: Verify
echo "=== RESULTS ==="
echo "SNPs in final VCF: $(bcftools view -H final_merged.vcf.gz | wc -l)"
echo "Samples in final VCF: $(bcftools query -l final_merged.vcf.gz | wc -l)"
echo ""
echo "Last 5 samples:"
bcftools query -l final_merged.vcf.gz | tail -5

# Cleanup temp files
rm -f leucopus_temp.vcf.gz maniculatus_temp.vcf.gz target_snps.txt
